#pragma once
#include "CMaths.hh"

typedef unsigned char undefined;

typedef unsigned char byte;
typedef unsigned int  dword;

typedef long long          longlong;
typedef unsigned long long qword;
typedef unsigned char      uchar;
typedef unsigned int       uint;
typedef unsigned long      ulong;
typedef unsigned long long ulonglong;
typedef unsigned char      undefined1;
typedef unsigned short     undefined2;
typedef unsigned int       undefined4;
typedef unsigned long long undefined8;
typedef unsigned short     ushort;

typedef unsigned short           word;
typedef struct CVehicleModelInfo CVehicleModelInfo, *PCVehicleModelInfo;

typedef struct CBaseModelInfo CBaseModelInfo, *PCBaseModelInfo;

typedef enum eVehicleType
{
    VEHICLE_TYPE_BIKE  = 1,
    VEHICLE_TYPE_BOAT  = 2,
    VEHICLE_TYPE_CAR   = 0,
    VEHICLE_TYPE_HELI  = 4,
    VEHICLE_TYPE_PLANE = 5,
    VEHICLE_TYPE_TRAIN = 3
} eVehicleType;

typedef struct CVehicleModelInfo_obj1 CVehicleModelInfo_obj1,
    *PCVehicleModelInfo_obj1;

typedef struct CVehicleModelInfo_obj2 CVehicleModelInfo_obj2,
    *PCVehicleModelInfo_obj2;

typedef struct CVirtualBase CVirtualBase, *PCVirtualBase;

typedef struct Vector3 Vector3, *PVector3;

typedef struct CBaseModelInfo__vftable CBaseModelInfo__vftable,
    *PCBaseModelInfo__vftable;

enum eModelInfoType : unsigned char
{
    MODEL_INFO_BASE    = 1,
    MODEL_INFO_MLO     = 2,
    MODEL_INFO_PED     = 6,
    MODEL_INFO_TIME    = 3,
    MODEL_INFO_VEHICLE = 5,
    MODEL_INFO_WEAPON  = 4
};

struct CVehicleModelInfo_obj2
{
    dword field_0;
    dword field_4;
    dword field_8;
};

struct CVirtualBase
{
    struct CBaseModelInfo__vftable *__vmt;
};


struct CBaseModelInfo : CVirtualBase
{ /* size = 0x60 */
    dword          field_4;
    dword          field_8;
    dword          field_C;
    dword          field_10; /* float */
    dword          field_14; /* float */
    dword          field_18; /* float */
    dword          field_1C;
    struct Vector3 m_vecMinBounds;
    dword          m_fDrawDistance;
    struct Vector3 m_vecMaxBounds;
    dword          m_nModelHash;
    dword          m_nBaseFlags;
    dword          m_dwRefCount;
    short          m_wTxd;
    word           field_4A;
    word           field_4C;
    word           field_4E;
    word           field_50;
    word           field_52;
    word           field_54;
    word           m_nAnims;
    word           m_wBlendshapeId;
    byte           field_5A;
    byte           field_5B;
    dword          field_5C;
};

struct CVehicleModelInfo_obj1
{
    struct Vector3 field_0;
    dword          field_C;
    byte           field_10;
    byte           field_11;
    undefined      field_0x12;
    undefined      field_0x13;
    dword          field_14;
    dword          field_18;
    dword          field_1C;
    dword          field_20;
    dword          field_24;
    dword          field_28;
    dword          field_2C;
};

struct CVehicleModelInfo : CBaseModelInfo
{
    char              m_szGameName[9];
    undefined         field_0x69;
    undefined         field_0x6a;
    undefined         field_0x6b;
    enum eVehicleType m_nType;
    enum eVehicleType m_nClassId;
    float             m_fWheelRadiusA2;
    float             m_fWheelRadiusB1; /* Created by retype action */
    float             m_fWheelRadiusA1;
    float             m_fWheelRadiusB2; /* Created by retype action */
    dword             m_nLodMult;
    dword             m_fSwankness; /* float */
    dword             m_dwHandlingIndex;
    undefined         field_0x90;
    undefined         field_0x91;
    undefined         field_0x92;
    undefined         field_0x93;
    dword             flags;
    int               field_0x98;
    float             m_fFrq;
    int               m_nMaxNum; /* Created by retype action */
    int               m_ndefDirtLevel;
    dword             m_nLastRemoved;
    dword             m_nPedGroup;
    dword             m_nSpawnCount;
    dword             field_B4; /* float */
    dword             field_B8; /* float */
    int               unkfloat_related;
    short             m_nAnim2;
    undefined         field_0xc2;
    undefined         field_0xc3;
    dword             field_C4;
    dword             field_C8;
    dword             field_CC;
    byte              m_aColours[4][25];
    dword             m_nTotalColours;
    dword             m_nCurrentColourId;
    dword             field_13C;
    dword             field_140;
    dword             field_144;
    dword             field_148;
    undefined         field_0x14c;
    undefined         field_0x14d;
    undefined         field_0x14e;
    undefined         field_0x14f;
    struct CVehicleModelInfo_obj1 field_150;
    undefined                     field_0x180;
    undefined                     field_0x181;
    undefined                     field_0x182;
    undefined                     field_0x183;
    undefined                     field_0x184;
    undefined                     field_0x185;
    undefined                     field_0x186;
    undefined                     field_0x187;
    undefined                     field_0x188;
    undefined                     field_0x189;
    undefined                     field_0x18a;
    undefined                     field_0x18b;
    undefined                     field_0x18c;
    undefined                     field_0x18d;
    undefined                     field_0x18e;
    undefined                     field_0x18f;
    undefined                     field_0x190;
    undefined                     field_0x191;
    undefined                     field_0x192;
    undefined                     field_0x193;
    undefined                     field_0x194;
    undefined                     field_0x195;
    undefined                     field_0x196;
    undefined                     field_0x197;
    undefined                     field_0x198;
    undefined                     field_0x199;
    undefined                     field_0x19a;
    undefined                     field_0x19b;
    undefined                     field_0x19c;
    undefined                     field_0x19d;
    undefined                     field_0x19e;
    undefined                     field_0x19f;
    undefined                     field_0x1a0;
    undefined                     field_0x1a1;
    undefined                     field_0x1a2;
    undefined                     field_0x1a3;
    undefined                     field_0x1a4;
    undefined                     field_0x1a5;
    undefined                     field_0x1a6;
    undefined                     field_0x1a7;
    undefined                     field_0x1a8;
    undefined                     field_0x1a9;
    undefined                     field_0x1aa;
    undefined                     field_0x1ab;
    undefined                     field_0x1ac;
    undefined                     field_0x1ad;
    undefined                     field_0x1ae;
    undefined                     field_0x1af;
    undefined                     field_0x1b0;
    undefined                     field_0x1b1;
    undefined                     field_0x1b2;
    undefined                     field_0x1b3;
    undefined                     field_0x1b4;
    undefined                     field_0x1b5;
    undefined                     field_0x1b6;
    undefined                     field_0x1b7;
    undefined                     field_0x1b8;
    undefined                     field_0x1b9;
    undefined                     field_0x1ba;
    undefined                     field_0x1bb;
    undefined                     field_0x1bc;
    undefined                     field_0x1bd;
    undefined                     field_0x1be;
    undefined                     field_0x1bf;
    undefined                     field_0x1c0;
    undefined                     field_0x1c1;
    undefined                     field_0x1c2;
    undefined                     field_0x1c3;
    undefined                     field_0x1c4;
    undefined                     field_0x1c5;
    undefined                     field_0x1c6;
    undefined                     field_0x1c7;
    undefined                     field_0x1c8;
    undefined                     field_0x1c9;
    undefined                     field_0x1ca;
    undefined                     field_0x1cb;
    undefined                     field_0x1cc;
    undefined                     field_0x1cd;
    undefined                     field_0x1ce;
    undefined                     field_0x1cf;
    undefined                     field_0x1d0;
    undefined                     field_0x1d1;
    undefined                     field_0x1d2;
    undefined                     field_0x1d3;
    undefined                     field_0x1d4;
    undefined                     field_0x1d5;
    undefined                     field_0x1d6;
    undefined                     field_0x1d7;
    undefined                     field_0x1d8;
    undefined                     field_0x1d9;
    undefined                     field_0x1da;
    undefined                     field_0x1db;
    undefined                     field_0x1dc;
    undefined                     field_0x1dd;
    undefined                     field_0x1de;
    undefined                     field_0x1df;
    undefined                     field_0x1e0;
    undefined                     field_0x1e1;
    undefined                     field_0x1e2;
    undefined                     field_0x1e3;
    undefined                     field_0x1e4;
    undefined                     field_0x1e5;
    undefined                     field_0x1e6;
    undefined                     field_0x1e7;
    undefined                     field_0x1e8;
    undefined                     field_0x1e9;
    undefined                     field_0x1ea;
    undefined                     field_0x1eb;
    undefined                     field_0x1ec;
    undefined                     field_0x1ed;
    undefined                     field_0x1ee;
    undefined                     field_0x1ef;
    undefined                     field_0x1f0;
    undefined                     field_0x1f1;
    undefined                     field_0x1f2;
    undefined                     field_0x1f3;
    undefined                     field_0x1f4;
    undefined                     field_0x1f5;
    undefined                     field_0x1f6;
    undefined                     field_0x1f7;
    undefined                     field_0x1f8;
    undefined                     field_0x1f9;
    undefined                     field_0x1fa;
    undefined                     field_0x1fb;
    undefined                     field_0x1fc;
    undefined                     field_0x1fd;
    undefined                     field_0x1fe;
    undefined                     field_0x1ff;
    undefined                     field_0x200;
    undefined                     field_0x201;
    undefined                     field_0x202;
    undefined                     field_0x203;
    undefined                     field_0x204;
    undefined                     field_0x205;
    undefined                     field_0x206;
    undefined                     field_0x207;
    undefined                     field_0x208;
    undefined                     field_0x209;
    undefined                     field_0x20a;
    undefined                     field_0x20b;
    undefined                     field_0x20c;
    undefined                     field_0x20d;
    undefined                     field_0x20e;
    undefined                     field_0x20f;
    undefined                     field_0x210;
    undefined                     field_0x211;
    undefined                     field_0x212;
    undefined                     field_0x213;
    undefined                     field_0x214;
    undefined                     field_0x215;
    undefined                     field_0x216;
    undefined                     field_0x217;
    undefined                     field_0x218;
    undefined                     field_0x219;
    undefined                     field_0x21a;
    undefined                     field_0x21b;
    undefined                     field_0x21c;
    undefined                     field_0x21d;
    undefined                     field_0x21e;
    undefined                     field_0x21f;
    undefined                     field_0x220;
    undefined                     field_0x221;
    undefined                     field_0x222;
    undefined                     field_0x223;
    undefined                     field_0x224;
    undefined                     field_0x225;
    undefined                     field_0x226;
    undefined                     field_0x227;
    undefined                     field_0x228;
    undefined                     field_0x229;
    undefined                     field_0x22a;
    undefined                     field_0x22b;
    undefined                     field_0x22c;
    undefined                     field_0x22d;
    undefined                     field_0x22e;
    undefined                     field_0x22f;
    undefined                     field_0x230;
    undefined                     field_0x231;
    undefined                     field_0x232;
    undefined                     field_0x233;
    undefined                     field_0x234;
    undefined                     field_0x235;
    undefined                     field_0x236;
    undefined                     field_0x237;
    undefined                     field_0x238;
    undefined                     field_0x239;
    undefined                     field_0x23a;
    undefined                     field_0x23b;
    undefined                     field_0x23c;
    undefined                     field_0x23d;
    undefined                     field_0x23e;
    undefined                     field_0x23f;
    undefined                     field_0x240;
    undefined                     field_0x241;
    undefined                     field_0x242;
    undefined                     field_0x243;
    undefined                     field_0x244;
    undefined                     field_0x245;
    undefined                     field_0x246;
    undefined                     field_0x247;
    undefined                     field_0x248;
    undefined                     field_0x249;
    undefined                     field_0x24a;
    undefined                     field_0x24b;
    undefined                     field_0x24c;
    undefined                     field_0x24d;
    undefined                     field_0x24e;
    undefined                     field_0x24f;
    undefined                     field_0x250;
    undefined                     field_0x251;
    undefined                     field_0x252;
    undefined                     field_0x253;
    undefined                     field_0x254;
    undefined                     field_0x255;
    undefined                     field_0x256;
    undefined                     field_0x257;
    undefined                     field_0x258;
    undefined                     field_0x259;
    undefined                     field_0x25a;
    undefined                     field_0x25b;
    undefined                     field_0x25c;
    undefined                     field_0x25d;
    undefined                     field_0x25e;
    undefined                     field_0x25f;
    undefined                     field_0x260;
    undefined                     field_0x261;
    undefined                     field_0x262;
    undefined                     field_0x263;
    undefined                     field_0x264;
    undefined                     field_0x265;
    undefined                     field_0x266;
    undefined                     field_0x267;
    undefined                     field_0x268;
    undefined                     field_0x269;
    undefined                     field_0x26a;
    undefined                     field_0x26b;
    undefined                     field_0x26c;
    undefined                     field_0x26d;
    undefined                     field_0x26e;
    undefined                     field_0x26f;
    undefined                     field_0x270;
    undefined                     field_0x271;
    undefined                     field_0x272;
    undefined                     field_0x273;
    undefined                     field_0x274;
    undefined                     field_0x275;
    undefined                     field_0x276;
    undefined                     field_0x277;
    undefined                     field_0x278;
    undefined                     field_0x279;
    undefined                     field_0x27a;
    undefined                     field_0x27b;
    undefined                     field_0x27c;
    undefined                     field_0x27d;
    undefined                     field_0x27e;
    undefined                     field_0x27f;
    undefined                     field_0x280;
    undefined                     field_0x281;
    undefined                     field_0x282;
    undefined                     field_0x283;
    undefined                     field_0x284;
    undefined                     field_0x285;
    undefined                     field_0x286;
    undefined                     field_0x287;
    undefined                     field_0x288;
    undefined                     field_0x289;
    undefined                     field_0x28a;
    undefined                     field_0x28b;
    undefined                     field_0x28c;
    undefined                     field_0x28d;
    undefined                     field_0x28e;
    undefined                     field_0x28f;
    undefined                     field_0x290;
    undefined                     field_0x291;
    undefined                     field_0x292;
    undefined                     field_0x293;
    undefined                     field_0x294;
    undefined                     field_0x295;
    undefined                     field_0x296;
    undefined                     field_0x297;
    undefined                     field_0x298;
    undefined                     field_0x299;
    undefined                     field_0x29a;
    undefined                     field_0x29b;
    undefined                     field_0x29c;
    undefined                     field_0x29d;
    undefined                     field_0x29e;
    undefined                     field_0x29f;
    undefined                     field_0x2a0;
    undefined                     field_0x2a1;
    undefined                     field_0x2a2;
    undefined                     field_0x2a3;
    undefined                     field_0x2a4;
    undefined                     field_0x2a5;
    undefined                     field_0x2a6;
    undefined                     field_0x2a7;
    undefined                     field_0x2a8;
    undefined                     field_0x2a9;
    undefined                     field_0x2aa;
    undefined                     field_0x2ab;
    undefined                     field_0x2ac;
    undefined                     field_0x2ad;
    undefined                     field_0x2ae;
    undefined                     field_0x2af;
    undefined                     field_0x2b0;
    undefined                     field_0x2b1;
    undefined                     field_0x2b2;
    undefined                     field_0x2b3;
    undefined                     field_0x2b4;
    undefined                     field_0x2b5;
    undefined                     field_0x2b6;
    undefined                     field_0x2b7;
    undefined                     field_0x2b8;
    undefined                     field_0x2b9;
    undefined                     field_0x2ba;
    undefined                     field_0x2bb;
    undefined                     field_0x2bc;
    undefined                     field_0x2bd;
    undefined                     field_0x2be;
    undefined                     field_0x2bf;
    undefined                     field_0x2c0;
    undefined                     field_0x2c1;
    undefined                     field_0x2c2;
    undefined                     field_0x2c3;
    undefined                     field_0x2c4;
    undefined                     field_0x2c5;
    undefined                     field_0x2c6;
    undefined                     field_0x2c7;
    undefined                     field_0x2c8;
    undefined                     field_0x2c9;
    undefined                     field_0x2ca;
    undefined                     field_0x2cb;
    undefined                     field_0x2cc;
    undefined                     field_0x2cd;
    undefined                     field_0x2ce;
    undefined                     field_0x2cf;
    undefined                     field_0x2d0;
    undefined                     field_0x2d1;
    undefined                     field_0x2d2;
    undefined                     field_0x2d3;
    undefined                     field_0x2d4;
    undefined                     field_0x2d5;
    undefined                     field_0x2d6;
    undefined                     field_0x2d7;
    undefined                     field_0x2d8;
    undefined                     field_0x2d9;
    undefined                     field_0x2da;
    undefined                     field_0x2db;
    undefined                     field_0x2dc;
    undefined                     field_0x2dd;
    undefined                     field_0x2de;
    undefined                     field_0x2df;
    undefined                     field_0x2e0;
    undefined                     field_0x2e1;
    undefined                     field_0x2e2;
    undefined                     field_0x2e3;
    undefined                     field_0x2e4;
    undefined                     field_0x2e5;
    undefined                     field_0x2e6;
    undefined                     field_0x2e7;
    undefined                     field_0x2e8;
    undefined                     field_0x2e9;
    undefined                     field_0x2ea;
    undefined                     field_0x2eb;
    undefined                     field_0x2ec;
    undefined                     field_0x2ed;
    undefined                     field_0x2ee;
    undefined                     field_0x2ef;
    undefined                     field_0x2f0;
    undefined                     field_0x2f1;
    undefined                     field_0x2f2;
    undefined                     field_0x2f3;
    undefined                     field_0x2f4;
    undefined                     field_0x2f5;
    undefined                     field_0x2f6;
    undefined                     field_0x2f7;
    undefined                     field_0x2f8;
    undefined                     field_0x2f9;
    undefined                     field_0x2fa;
    undefined                     field_0x2fb;
    undefined                     field_0x2fc;
    undefined                     field_0x2fd;
    undefined                     field_0x2fe;
    undefined                     field_0x2ff;
    undefined                     field_0x300;
    undefined                     field_0x301;
    undefined                     field_0x302;
    undefined                     field_0x303;
    undefined                     field_0x304;
    undefined                     field_0x305;
    undefined                     field_0x306;
    undefined                     field_0x307;
    undefined                     field_0x308;
    undefined                     field_0x309;
    undefined                     field_0x30a;
    undefined                     field_0x30b;
    undefined                     field_0x30c;
    undefined                     field_0x30d;
    undefined                     field_0x30e;
    undefined                     field_0x30f;
    undefined                     field_0x310;
    undefined                     field_0x311;
    undefined                     field_0x312;
    undefined                     field_0x313;
    undefined                     field_0x314;
    undefined                     field_0x315;
    undefined                     field_0x316;
    undefined                     field_0x317;
    undefined                     field_0x318;
    undefined                     field_0x319;
    undefined                     field_0x31a;
    undefined                     field_0x31b;
    undefined                     field_0x31c;
    undefined                     field_0x31d;
    undefined                     field_0x31e;
    undefined                     field_0x31f;
    undefined                     field_0x320;
    undefined                     field_0x321;
    undefined                     field_0x322;
    undefined                     field_0x323;
    undefined                     field_0x324;
    undefined                     field_0x325;
    undefined                     field_0x326;
    undefined                     field_0x327;
    undefined                     field_0x328;
    undefined                     field_0x329;
    undefined                     field_0x32a;
    undefined                     field_0x32b;
    undefined                     field_0x32c;
    undefined                     field_0x32d;
    undefined                     field_0x32e;
    undefined                     field_0x32f;
    dword                         field_330;
    float                         field_334; /* float */
    dword                         field_338; /* float */
    dword                         field_33C; /* float */
    dword                         field_340; /* float */
    dword                         field_344; /* float */
    dword                         field_348; /* float */
    dword                         field_34C;
    struct CVehicleModelInfo_obj2 field_350;
    undefined                     field_0x35c;
    undefined                     field_0x35d;
    undefined                     field_0x35e;
    undefined                     field_0x35f;
    undefined                     field_0x360;
    undefined                     field_0x361;
    undefined                     field_0x362;
    undefined                     field_0x363;
    undefined                     field_0x364;
    undefined                     field_0x365;
    undefined                     field_0x366;
    undefined                     field_0x367;
    undefined                     field_0x368;
    undefined                     field_0x369;
    undefined                     field_0x36a;
    undefined                     field_0x36b;
    undefined                     field_0x36c;
    undefined                     field_0x36d;
    undefined                     field_0x36e;
    undefined                     field_0x36f;
    undefined                     field_0x370;
    undefined                     field_0x371;
    undefined                     field_0x372;
    undefined                     field_0x373;
    undefined                     field_0x374;
    undefined                     field_0x375;
    undefined                     field_0x376;
    undefined                     field_0x377;
    undefined                     field_0x378;
    undefined                     field_0x379;
    undefined                     field_0x37a;
    undefined                     field_0x37b;
    undefined                     field_0x37c;
    undefined                     field_0x37d;
    undefined                     field_0x37e;
    undefined                     field_0x37f;
    undefined                     field_0x380;
    undefined                     field_0x381;
    undefined                     field_0x382;
    undefined                     field_0x383;
    undefined                     field_0x384;
    undefined                     field_0x385;
    undefined                     field_0x386;
    undefined                     field_0x387;
    undefined                     field_0x388;
    undefined                     field_0x389;
    undefined                     field_0x38a;
    undefined                     field_0x38b;
    undefined                     field_0x38c;
    undefined                     field_0x38d;
    undefined                     field_0x38e;
    undefined                     field_0x38f;
    undefined                     field_0x390;
    undefined                     field_0x391;
    undefined                     field_0x392;
    undefined                     field_0x393;
    undefined                     field_0x394;
    undefined                     field_0x395;
    undefined                     field_0x396;
    undefined                     field_0x397;
    undefined                     field_0x398;
    undefined                     field_0x399;
    undefined                     field_0x39a;
    undefined                     field_0x39b;
    undefined                     field_0x39c;
    undefined                     field_0x39d;
    undefined                     field_0x39e;
    undefined                     field_0x39f;
    undefined                     field_0x3a0;
    undefined                     field_0x3a1;
    undefined                     field_0x3a2;
    undefined                     field_0x3a3;
    undefined                     field_0x3a4;
    undefined                     field_0x3a5;
    undefined                     field_0x3a6;
    undefined                     field_0x3a7;
    undefined                     field_0x3a8;
    undefined                     field_0x3a9;
    undefined                     field_0x3aa;
    undefined                     field_0x3ab;
    undefined                     field_0x3ac;
    undefined                     field_0x3ad;
    undefined                     field_0x3ae;
    undefined                     field_0x3af;
    undefined                     field_0x3b0;
    undefined                     field_0x3b1;
    undefined                     field_0x3b2;
    undefined                     field_0x3b3;
    undefined                     field_0x3b4;
    undefined                     field_0x3b5;
    undefined                     field_0x3b6;
    undefined                     field_0x3b7;
    undefined                     field_0x3b8;
    undefined                     field_0x3b9;
    undefined                     field_0x3ba;
    undefined                     field_0x3bb;
    dword                         field_3BC;
    byte                          field_3C0;
    undefined                     field_0x3c1;
    undefined                     field_0x3c2;
    undefined                     field_0x3c3;
    word                          field_3C4;
    byte                          field_3C6;
    byte                          field_3C7;
};

struct CPedModelInfo : CBaseModelInfo
{ /* size = 0x160 */
    dword     field_60;
    dword     field_64;
    dword     field_68;
    dword     field_6C;
    dword     field_70;
    dword     field_74;
    dword     field_78;
    dword     field_7C;
    dword     m_nGestureGroup;
    dword     m_nFacialGroup;
    int       m_nVisemeGroup;
    bool      m_nPlayerPedType; /* Created by retype action */
    undefined field_0x8d;
    undefined field_0x8e;
    undefined field_0x8f;
    dword     m_nPedType;
    dword     field_94;
    word      field_98;
    word      m_nFlags;
    int       field_0x9c;
    dword     m_nLastLoaded;
    dword     field_A4;
    dword     field_A8;
    dword     m_nUses;
    byte      m_bRadio2;
    byte      m_bRadio;
    byte      field_B2;
    undefined field_0xb3;
    word      field_B4;
    word      field_B6;
    word      field_B8;
    word      field_BA;
    dword     m_nFirstVoiceHash;
    byte      field_C0;
    undefined field_0xc1;
    undefined field_0xc2;
    undefined field_0xc3;
    undefined field_0xc4;
    undefined field_0xc5;
    undefined field_0xc6;
    undefined field_0xc7;
    undefined field_0xc8;
    undefined field_0xc9;
    undefined field_0xca;
    undefined field_0xcb;
    undefined field_0xcc;
    undefined field_0xcd;
    undefined field_0xce;
    undefined field_0xcf;
    undefined field_0xd0;
    undefined field_0xd1;
    undefined field_0xd2;
    undefined field_0xd3;
    undefined field_0xd4;
    undefined field_0xd5;
    undefined field_0xd6;
    undefined field_0xd7;
    undefined field_0xd8;
    undefined field_0xd9;
    undefined field_0xda;
    undefined field_0xdb;
    undefined field_0xdc;
    undefined field_0xdd;
    undefined field_0xde;
    undefined field_0xdf;
    undefined field_0xe0;
    undefined field_0xe1;
    undefined field_0xe2;
    undefined field_0xe3;
    undefined field_0xe4;
    undefined field_0xe5;
    undefined field_0xe6;
    undefined field_0xe7;
    dword     field_E8;
    byte      m_nbAge;
    byte      m_nbSexiness;
    byte      m_nbBravery;
    byte      m_nbAgility;
    byte      m_e1stLanguage;
    byte      m_e2ndLanguage;
    undefined field_0xf2;
    undefined field_0xf3;
    dword     m_fAttack;                   /* float */
    dword     m_fDefend;                   /* float */
    dword     m_fMeleeMartialLevelPercent; /* float */
    dword     field_100;                   /* animation inidces or pointers */
    undefined field_0x104;
    undefined field_0x105;
    undefined field_0x106;
    undefined field_0x107;
    undefined field_0x108;
    undefined field_0x109;
    undefined field_0x10a;
    undefined field_0x10b;
    undefined field_0x10c;
    undefined field_0x10d;
    undefined field_0x10e;
    undefined field_0x10f;
    undefined field_0x110;
    undefined field_0x111;
    undefined field_0x112;
    undefined field_0x113;
    undefined field_0x114;
    undefined field_0x115;
    undefined field_0x116;
    undefined field_0x117;
    undefined field_0x118;
    undefined field_0x119;
    undefined field_0x11a;
    undefined field_0x11b;
    dword     field_11C; /* animation index or pointer */
    dword     m_dwPersonalityFlagsL;
    dword     m_dwPersonalityFlagsH;
    dword     field_128;
    dword     field_12C;
    dword     field_130;
    byte      field_134;
    undefined field_0x135;
    undefined field_0x136;
    undefined field_0x137;
    undefined field_0x138;
    undefined field_0x139;
    undefined field_0x13a;
    undefined field_0x13b;
    undefined field_0x13c;
    undefined field_0x13d;
    undefined field_0x13e;
    undefined field_0x13f;
    undefined field_0x140;
    undefined field_0x141;
    undefined field_0x142;
    undefined field_0x143;
    undefined field_0x144;
    undefined field_0x145;
    undefined field_0x146;
    undefined field_0x147;
    undefined field_0x148;
    undefined field_0x149;
    undefined field_0x14a;
    undefined field_0x14b;
    undefined field_0x14c;
    undefined field_0x14d;
    undefined field_0x14e;
    undefined field_0x14f;
    undefined field_0x150;
    undefined field_0x151;
    undefined field_0x152;
    undefined field_0x153;
    undefined field_0x154;
    undefined field_0x155;
    undefined field_0x156;
    undefined field_0x157;
    byte      field_158;
    byte      field_159;
    undefined field_0x15a;
    undefined field_0x15b;
    dword     field_15C;
};

struct CBaseModelInfo__vftable
{
    void *deconstructor;
    void *Initialise;
    void *m8;
    eModelInfoType (*GetType) (void);
    void *m10;
    void *m14;
    void *m18;
    void *m1c;
    void *m20;
    void *m24;
    void *m28;
    void *m2C;
    void *m30;
    void *m34;
    void *m38;
};
