#pragma once

typedef unsigned char      undefined;
typedef unsigned char      byte;
typedef unsigned int       dword;
typedef long long          longlong;
typedef unsigned long long qword;
typedef unsigned char      uchar;
typedef unsigned int       uint;
typedef unsigned long      ulong;
typedef unsigned long long ulonglong;
typedef unsigned char      undefined1;
typedef unsigned short     undefined2;
typedef unsigned int       undefined4;
typedef unsigned long long undefined8;
typedef unsigned short     ushort;
typedef unsigned short     word;
typedef struct CWeaponInfo CWeaponInfo, *PCWeaponInfo;

class CWeaponInfo
{
public:
    
    undefined4 type;
    undefined4 slot;
    int        fireType;
    undefined4 damageType;
    undefined4 group;
    float      targetRange;
    float      weaponRange;
    undefined4 statType;
    uint       flags;
    undefined4 m_nWeaponModelHash;
    undefined4 animGroup;
    float      animFireRate;
    float      animBlindFireRate;
    float      field_0x34;
    float      field_0x38;
    undefined  field_0x3c;
    undefined  field_0x3d;
    undefined  field_0x3e;
    undefined  field_0x3f;
    undefined  field_0x40;
    undefined  field_0x41;
    undefined  field_0x42;
    undefined  field_0x43;
    undefined  field_0x44;
    undefined  field_0x45;
    undefined  field_0x46;
    undefined  field_0x47;
    undefined  field_0x48;
    undefined  field_0x49;
    undefined  field_0x4a;
    undefined  field_0x4b;
    undefined  field_0x4c;
    undefined  field_0x4d;
    undefined  field_0x4e;
    undefined  field_0x4f;
    undefined  field_0x50;
    undefined  field_0x51;
    undefined  field_0x52;
    undefined  field_0x53;
    undefined  field_0x54;
    undefined  field_0x55;
    undefined  field_0x56;
    undefined  field_0x57;
    undefined  field_0x58;
    undefined  field_0x59;
    undefined  field_0x5a;
    undefined  field_0x5b;
    undefined  field_0x5c;
    undefined  field_0x5d;
    undefined  field_0x5e;
    undefined  field_0x5f;
    float      field_0x60;
    float      field_0x64;
    float      field_0x68;
    float      field_0x6c;
    undefined4 rumbleDuration;
    float      rumbleIntensity;
    undefined4 regenTime;
    undefined  field_0x7c;
    undefined  field_0x7d;
    undefined  field_0x7e;
    undefined  field_0x7f;
    undefined2 ammoonstreet;
    undefined2 base;
    undefined2 fps;
    undefined2 clipSize;
    short      ammoMax;
    undefined  field_0x8a;
    undefined  field_0x8b;
    undefined4 timeBetweenShots;
    float      force;
    undefined4 time;
    undefined4 fastTime;
    undefined4 crouchTime;
    undefined4 m_bDisplayOnHUD;
    undefined4 field_0xa4;
    undefined4 field_0xa8;
    undefined4 field_0xac;
    undefined  field_0xb0;
    undefined  field_0xb1;
    undefined  field_0xb2;
    undefined  field_0xb3;
    undefined  field_0xb4;
    undefined  field_0xb5;
    undefined  field_0xb6;
    undefined  field_0xb7;
    undefined  field_0xb8;
    undefined  field_0xb9;
    undefined  field_0xba;
    undefined  field_0xbb;
    undefined  field_0xbc;
    undefined  field_0xbd;
    undefined  field_0xbe;
    undefined  field_0xbf;
    undefined  field_0xc0;
    undefined  field_0xc1;
    undefined  field_0xc2;
    undefined  field_0xc3;
    undefined  field_0xc4;
    undefined  field_0xc5;
    undefined  field_0xc6;
    undefined  field_0xc7;
    undefined  field_0xc8;
    undefined  field_0xc9;
    undefined  field_0xca;
    undefined  field_0xcb;
    undefined  field_0xcc;
    undefined  field_0xcd;
    undefined  field_0xce;
    undefined  field_0xcf;
    float      field_0xd0;
    float      field_0xd4;
    float      field_0xd8;
    undefined4 animMeleeGroup1;
    undefined4 animMeleeGroup2;
    undefined4 muzzleFx;
    undefined4 shellFx;
    undefined4 trailFx;
    float      field_0xf0;
    float      field_0xf4;
    undefined  field_0xf8;
    undefined  field_0xf9;
    undefined  field_0xfa;
    undefined  field_0xfb;
    undefined  field_0xfc;
    undefined  field_0xfd;
    undefined  field_0xfe;
    undefined  field_0xff;
    
    static CWeaponInfo* GetInfoFromIndex(int index);

    static void InitialisePatterns();
};
